spring:
  application:
    name: IntelliDocAI Backend

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    # --- Producer Settings ---
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    # --- Consumer Settings ---
    consumer:
      group-id: intellidoc-workers
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # Crucial: Allow deserializing your specific DTOs
        spring.json.trusted.packages: "com.intellidocAI.backend.dto"
        spring.json.value.default.type: "com.intellidocAI.backend.dto.RepositoryProcessingRequest"

    # --- MAIN KAFKA PROPERTIES (including Security) ---
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: ${KAFKA_JAAS_CONFIG}

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE_NAME}
      auto-index-creation: true

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

repo.clone.path: ${REPO_CLONE_PATH}

app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationMs: 86400000
  otpExpirationMinutes: ${OTP_EXPIRATION_MINUTES:10}


server:
  port: 8080

# GitHub OAuth
github:
  client:
    id: ${GITHUB_CLIENT_ID}
    secret: ${GITHUB_CLIENT_SECRET}

# AI Service URL
ai:
  service:
    url: ${AI_SERVICE_URL:http://localhost:8000}